//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.TiMingCe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetStudentTiMingCeDataRequest", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.Request")]
    [System.SerializableAttribute()]
    public partial class GetStudentTiMingCeDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.ArtsOrScienceEnum ArtsOrScienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvinceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.ArtsOrScienceEnum ArtsOrScience {
            get {
                return this.ArtsOrScienceField;
            }
            set {
                if ((this.ArtsOrScienceField.Equals(value) != true)) {
                    this.ArtsOrScienceField = value;
                    this.RaisePropertyChanged("ArtsOrScience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvinceId {
            get {
                return this.ProvinceIdField;
            }
            set {
                if ((this.ProvinceIdField.Equals(value) != true)) {
                    this.ProvinceIdField = value;
                    this.RaisePropertyChanged("ProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArtsOrScienceEnum", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.Enum.TiMingCe")]
    public enum ArtsOrScienceEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arts = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Science = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Test.TiMingCe.ServiceResultOfbase64Binary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Test.TiMingCe.ServiceResultOfTiMingCeEntityTca8ElYk))]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSucceedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSucceed {
            get {
                return this.IsSucceedField;
            }
            set {
                if ((this.IsSucceedField.Equals(value) != true)) {
                    this.IsSucceedField = value;
                    this.RaisePropertyChanged("IsSucceed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfbase64Binary", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.Common")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfbase64Binary : Test.TiMingCe.ServiceResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EntityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfTiMingCeEntityTca8ElYk", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.Common")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfTiMingCeEntityTca8ElYk : Test.TiMingCe.ServiceResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.TiMingCeEntity EntityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.TiMingCeEntity Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiMingCeEntity", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.View")]
    [System.SerializableAttribute()]
    public partial class TiMingCeEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.ArtsOrScienceEnum ArtsOrScienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.GaoKaoScorePredictionEntity[] CourseScorePredictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NextGaoKaoDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.PassingStageScoreLineEntity[] PassingStageScoreLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PredictionYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvinceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.GaoKaoRankingEntity RankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, int> ScoreDistributionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentCountOfBelowUndergraduateFirstBatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.UniversitySignUpEntity UniversitySignUpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.ArtsOrScienceEnum ArtsOrScience {
            get {
                return this.ArtsOrScienceField;
            }
            set {
                if ((this.ArtsOrScienceField.Equals(value) != true)) {
                    this.ArtsOrScienceField = value;
                    this.RaisePropertyChanged("ArtsOrScience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.GaoKaoScorePredictionEntity[] CourseScorePredictions {
            get {
                return this.CourseScorePredictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseScorePredictionsField, value) != true)) {
                    this.CourseScorePredictionsField = value;
                    this.RaisePropertyChanged("CourseScorePredictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextGaoKaoDate {
            get {
                return this.NextGaoKaoDateField;
            }
            set {
                if ((this.NextGaoKaoDateField.Equals(value) != true)) {
                    this.NextGaoKaoDateField = value;
                    this.RaisePropertyChanged("NextGaoKaoDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.PassingStageScoreLineEntity[] PassingStageScoreLines {
            get {
                return this.PassingStageScoreLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.PassingStageScoreLinesField, value) != true)) {
                    this.PassingStageScoreLinesField = value;
                    this.RaisePropertyChanged("PassingStageScoreLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PredictionYear {
            get {
                return this.PredictionYearField;
            }
            set {
                if ((this.PredictionYearField.Equals(value) != true)) {
                    this.PredictionYearField = value;
                    this.RaisePropertyChanged("PredictionYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvinceId {
            get {
                return this.ProvinceIdField;
            }
            set {
                if ((this.ProvinceIdField.Equals(value) != true)) {
                    this.ProvinceIdField = value;
                    this.RaisePropertyChanged("ProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvinceName {
            get {
                return this.ProvinceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceNameField, value) != true)) {
                    this.ProvinceNameField = value;
                    this.RaisePropertyChanged("ProvinceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.GaoKaoRankingEntity Ranking {
            get {
                return this.RankingField;
            }
            set {
                if ((object.ReferenceEquals(this.RankingField, value) != true)) {
                    this.RankingField = value;
                    this.RaisePropertyChanged("Ranking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, int> ScoreDistribution {
            get {
                return this.ScoreDistributionField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreDistributionField, value) != true)) {
                    this.ScoreDistributionField = value;
                    this.RaisePropertyChanged("ScoreDistribution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentCountOfBelowUndergraduateFirstBatch {
            get {
                return this.StudentCountOfBelowUndergraduateFirstBatchField;
            }
            set {
                if ((this.StudentCountOfBelowUndergraduateFirstBatchField.Equals(value) != true)) {
                    this.StudentCountOfBelowUndergraduateFirstBatchField = value;
                    this.RaisePropertyChanged("StudentCountOfBelowUndergraduateFirstBatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.UniversitySignUpEntity UniversitySignUp {
            get {
                return this.UniversitySignUpField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversitySignUpField, value) != true)) {
                    this.UniversitySignUpField = value;
                    this.RaisePropertyChanged("UniversitySignUp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GaoKaoRankingEntity", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.View")]
    [System.SerializableAttribute()]
    public partial class GaoKaoRankingEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankingChangeOfImprovementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankingChangeOfScoreDecrementLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankingChangeOfScoreIncreaseLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentCountOfTheRankingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ranking {
            get {
                return this.RankingField;
            }
            set {
                if ((this.RankingField.Equals(value) != true)) {
                    this.RankingField = value;
                    this.RaisePropertyChanged("Ranking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RankingChangeOfImprovement {
            get {
                return this.RankingChangeOfImprovementField;
            }
            set {
                if ((this.RankingChangeOfImprovementField.Equals(value) != true)) {
                    this.RankingChangeOfImprovementField = value;
                    this.RaisePropertyChanged("RankingChangeOfImprovement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RankingChangeOfScoreDecrementLevel {
            get {
                return this.RankingChangeOfScoreDecrementLevelField;
            }
            set {
                if ((this.RankingChangeOfScoreDecrementLevelField.Equals(value) != true)) {
                    this.RankingChangeOfScoreDecrementLevelField = value;
                    this.RaisePropertyChanged("RankingChangeOfScoreDecrementLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RankingChangeOfScoreIncreaseLevel {
            get {
                return this.RankingChangeOfScoreIncreaseLevelField;
            }
            set {
                if ((this.RankingChangeOfScoreIncreaseLevelField.Equals(value) != true)) {
                    this.RankingChangeOfScoreIncreaseLevelField = value;
                    this.RaisePropertyChanged("RankingChangeOfScoreIncreaseLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentCountOfTheRanking {
            get {
                return this.StudentCountOfTheRankingField;
            }
            set {
                if ((this.StudentCountOfTheRankingField.Equals(value) != true)) {
                    this.StudentCountOfTheRankingField = value;
                    this.RaisePropertyChanged("StudentCountOfTheRanking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversitySignUpEntity", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.View")]
    [System.SerializableAttribute()]
    public partial class UniversitySignUpEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.RecommendUniversityEntity AccessibleUniversityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.RecommendUniversityEntity[] ConfidentUniversitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.RecommendUniversityEntity[] DreamyUniversitiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.RecommendUniversityEntity AccessibleUniversity {
            get {
                return this.AccessibleUniversityField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessibleUniversityField, value) != true)) {
                    this.AccessibleUniversityField = value;
                    this.RaisePropertyChanged("AccessibleUniversity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.RecommendUniversityEntity[] ConfidentUniversities {
            get {
                return this.ConfidentUniversitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidentUniversitiesField, value) != true)) {
                    this.ConfidentUniversitiesField = value;
                    this.RaisePropertyChanged("ConfidentUniversities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.RecommendUniversityEntity[] DreamyUniversities {
            get {
                return this.DreamyUniversitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.DreamyUniversitiesField, value) != true)) {
                    this.DreamyUniversitiesField = value;
                    this.RaisePropertyChanged("DreamyUniversities");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GaoKaoScorePredictionEntity", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.View")]
    [System.SerializableAttribute()]
    public partial class GaoKaoScorePredictionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.KnowledgePointScoreEstimation[] ImprovementPlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.StudentExamKnowledgePointAssessmentView[] PredictionKnowledgePointAssessmentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseShortName {
            get {
                return this.CourseShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseShortNameField, value) != true)) {
                    this.CourseShortNameField = value;
                    this.RaisePropertyChanged("CourseShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.KnowledgePointScoreEstimation[] ImprovementPlan {
            get {
                return this.ImprovementPlanField;
            }
            set {
                if ((object.ReferenceEquals(this.ImprovementPlanField, value) != true)) {
                    this.ImprovementPlanField = value;
                    this.RaisePropertyChanged("ImprovementPlan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.StudentExamKnowledgePointAssessmentView[] PredictionKnowledgePointAssessments {
            get {
                return this.PredictionKnowledgePointAssessmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PredictionKnowledgePointAssessmentsField, value) != true)) {
                    this.PredictionKnowledgePointAssessmentsField = value;
                    this.RaisePropertyChanged("PredictionKnowledgePointAssessments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PassingStageScoreLineEntity", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.View")]
    [System.SerializableAttribute()]
    public partial class PassingStageScoreLineEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableSchoolCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfEnrollmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreLineDifferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.UniversityStageEnum StageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableSchoolCount {
            get {
                return this.AvailableSchoolCountField;
            }
            set {
                if ((this.AvailableSchoolCountField.Equals(value) != true)) {
                    this.AvailableSchoolCountField = value;
                    this.RaisePropertyChanged("AvailableSchoolCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfEnrollments {
            get {
                return this.NumberOfEnrollmentsField;
            }
            set {
                if ((this.NumberOfEnrollmentsField.Equals(value) != true)) {
                    this.NumberOfEnrollmentsField = value;
                    this.RaisePropertyChanged("NumberOfEnrollments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreLine {
            get {
                return this.ScoreLineField;
            }
            set {
                if ((this.ScoreLineField.Equals(value) != true)) {
                    this.ScoreLineField = value;
                    this.RaisePropertyChanged("ScoreLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreLineDifference {
            get {
                return this.ScoreLineDifferenceField;
            }
            set {
                if ((this.ScoreLineDifferenceField.Equals(value) != true)) {
                    this.ScoreLineDifferenceField = value;
                    this.RaisePropertyChanged("ScoreLineDifference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.UniversityStageEnum Stage {
            get {
                return this.StageField;
            }
            set {
                if ((this.StageField.Equals(value) != true)) {
                    this.StageField = value;
                    this.RaisePropertyChanged("Stage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KnowledgePointScoreEstimation", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.EvaluationTool")]
    [System.SerializableAttribute()]
    public partial class KnowledgePointScoreEstimation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChildrenKnowledgePointNameDisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ChildrenKnowledgePointNameListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ChildrenKnowledgePointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FutureScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPredictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KnowledgePointFullPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KnowledgePointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KnowledgePointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentKnowledgePointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PointsToGainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsToGainDisplayChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.KnowledgePointScoreEstimation[] PreKnowledgePointScoreEstimationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] PreKnowledgePointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuestionLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SortingScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChildrenKnowledgePointNameDisplay {
            get {
                return this.ChildrenKnowledgePointNameDisplayField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenKnowledgePointNameDisplayField, value) != true)) {
                    this.ChildrenKnowledgePointNameDisplayField = value;
                    this.RaisePropertyChanged("ChildrenKnowledgePointNameDisplay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ChildrenKnowledgePointNameList {
            get {
                return this.ChildrenKnowledgePointNameListField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenKnowledgePointNameListField, value) != true)) {
                    this.ChildrenKnowledgePointNameListField = value;
                    this.RaisePropertyChanged("ChildrenKnowledgePointNameList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ChildrenKnowledgePoints {
            get {
                return this.ChildrenKnowledgePointsField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenKnowledgePointsField, value) != true)) {
                    this.ChildrenKnowledgePointsField = value;
                    this.RaisePropertyChanged("ChildrenKnowledgePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FutureScore {
            get {
                return this.FutureScoreField;
            }
            set {
                if ((this.FutureScoreField.Equals(value) != true)) {
                    this.FutureScoreField = value;
                    this.RaisePropertyChanged("FutureScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPredict {
            get {
                return this.IsPredictField;
            }
            set {
                if ((this.IsPredictField.Equals(value) != true)) {
                    this.IsPredictField = value;
                    this.RaisePropertyChanged("IsPredict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KnowledgePointFullPoint {
            get {
                return this.KnowledgePointFullPointField;
            }
            set {
                if ((this.KnowledgePointFullPointField.Equals(value) != true)) {
                    this.KnowledgePointFullPointField = value;
                    this.RaisePropertyChanged("KnowledgePointFullPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KnowledgePointId {
            get {
                return this.KnowledgePointIdField;
            }
            set {
                if ((this.KnowledgePointIdField.Equals(value) != true)) {
                    this.KnowledgePointIdField = value;
                    this.RaisePropertyChanged("KnowledgePointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KnowledgePointName {
            get {
                return this.KnowledgePointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KnowledgePointNameField, value) != true)) {
                    this.KnowledgePointNameField = value;
                    this.RaisePropertyChanged("KnowledgePointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentKnowledgePointName {
            get {
                return this.ParentKnowledgePointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentKnowledgePointNameField, value) != true)) {
                    this.ParentKnowledgePointNameField = value;
                    this.RaisePropertyChanged("ParentKnowledgePointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PointsToGain {
            get {
                return this.PointsToGainField;
            }
            set {
                if ((this.PointsToGainField.Equals(value) != true)) {
                    this.PointsToGainField = value;
                    this.RaisePropertyChanged("PointsToGain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointsToGainDisplayChange {
            get {
                return this.PointsToGainDisplayChangeField;
            }
            set {
                if ((this.PointsToGainDisplayChangeField.Equals(value) != true)) {
                    this.PointsToGainDisplayChangeField = value;
                    this.RaisePropertyChanged("PointsToGainDisplayChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.KnowledgePointScoreEstimation[] PreKnowledgePointScoreEstimation {
            get {
                return this.PreKnowledgePointScoreEstimationField;
            }
            set {
                if ((object.ReferenceEquals(this.PreKnowledgePointScoreEstimationField, value) != true)) {
                    this.PreKnowledgePointScoreEstimationField = value;
                    this.RaisePropertyChanged("PreKnowledgePointScoreEstimation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] PreKnowledgePoints {
            get {
                return this.PreKnowledgePointsField;
            }
            set {
                if ((object.ReferenceEquals(this.PreKnowledgePointsField, value) != true)) {
                    this.PreKnowledgePointsField = value;
                    this.RaisePropertyChanged("PreKnowledgePoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QuestionLevel {
            get {
                return this.QuestionLevelField;
            }
            set {
                if ((this.QuestionLevelField.Equals(value) != true)) {
                    this.QuestionLevelField = value;
                    this.RaisePropertyChanged("QuestionLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SortingScore {
            get {
                return this.SortingScoreField;
            }
            set {
                if ((this.SortingScoreField.Equals(value) != true)) {
                    this.SortingScoreField = value;
                    this.RaisePropertyChanged("SortingScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentExamKnowledgePointAssessmentView", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.EvaluationTool.Result")]
    [System.SerializableAttribute()]
    public partial class StudentExamKnowledgePointAssessmentView : Test.TiMingCe.KnowledgePointPoint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PredictionRulerFullPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PredictionRulerStudentScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StudentScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PredictionRulerFullPoint {
            get {
                return this.PredictionRulerFullPointField;
            }
            set {
                if ((this.PredictionRulerFullPointField.Equals(value) != true)) {
                    this.PredictionRulerFullPointField = value;
                    this.RaisePropertyChanged("PredictionRulerFullPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PredictionRulerStudentScore {
            get {
                return this.PredictionRulerStudentScoreField;
            }
            set {
                if ((this.PredictionRulerStudentScoreField.Equals(value) != true)) {
                    this.PredictionRulerStudentScoreField = value;
                    this.RaisePropertyChanged("PredictionRulerStudentScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StudentScore {
            get {
                return this.StudentScoreField;
            }
            set {
                if ((this.StudentScoreField.Equals(value) != true)) {
                    this.StudentScoreField = value;
                    this.RaisePropertyChanged("StudentScore");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KnowledgePointPoint", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.EvaluationTool")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Test.TiMingCe.StudentExamKnowledgePointAssessmentView))]
    public partial class KnowledgePointPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KnowledgePointFullPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KnowledgePointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KnowledgePointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentKnowledgePointNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuestionLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.KnowledgePointPointQuestion[] RelatedQuestionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KnowledgePointFullPoint {
            get {
                return this.KnowledgePointFullPointField;
            }
            set {
                if ((this.KnowledgePointFullPointField.Equals(value) != true)) {
                    this.KnowledgePointFullPointField = value;
                    this.RaisePropertyChanged("KnowledgePointFullPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KnowledgePointId {
            get {
                return this.KnowledgePointIdField;
            }
            set {
                if ((this.KnowledgePointIdField.Equals(value) != true)) {
                    this.KnowledgePointIdField = value;
                    this.RaisePropertyChanged("KnowledgePointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KnowledgePointName {
            get {
                return this.KnowledgePointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KnowledgePointNameField, value) != true)) {
                    this.KnowledgePointNameField = value;
                    this.RaisePropertyChanged("KnowledgePointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentKnowledgePointName {
            get {
                return this.ParentKnowledgePointNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentKnowledgePointNameField, value) != true)) {
                    this.ParentKnowledgePointNameField = value;
                    this.RaisePropertyChanged("ParentKnowledgePointName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QuestionLevel {
            get {
                return this.QuestionLevelField;
            }
            set {
                if ((this.QuestionLevelField.Equals(value) != true)) {
                    this.QuestionLevelField = value;
                    this.RaisePropertyChanged("QuestionLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.KnowledgePointPointQuestion[] RelatedQuestions {
            get {
                return this.RelatedQuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedQuestionsField, value) != true)) {
                    this.RelatedQuestionsField = value;
                    this.RaisePropertyChanged("RelatedQuestions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KnowledgePointPointQuestion", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.EvaluationTool")]
    [System.SerializableAttribute()]
    public partial class KnowledgePointPointQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.QuestionSimplifiedFormat QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.QuestionSimplifiedFormat Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionSimplifiedFormat", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.EvaluationTool")]
    [System.SerializableAttribute()]
    public partial class QuestionSimplifiedFormat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinishTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KnowledgePointLabelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MainKnowledgePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionDisplayTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short QuestionLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuestionQualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuestionSortingScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SupportOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseRangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] UseRangeIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinishTime {
            get {
                return this.FinishTimeField;
            }
            set {
                if ((this.FinishTimeField.Equals(value) != true)) {
                    this.FinishTimeField = value;
                    this.RaisePropertyChanged("FinishTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KnowledgePointLabels {
            get {
                return this.KnowledgePointLabelsField;
            }
            set {
                if ((object.ReferenceEquals(this.KnowledgePointLabelsField, value) != true)) {
                    this.KnowledgePointLabelsField = value;
                    this.RaisePropertyChanged("KnowledgePointLabels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MainKnowledgePoint {
            get {
                return this.MainKnowledgePointField;
            }
            set {
                if ((this.MainKnowledgePointField.Equals(value) != true)) {
                    this.MainKnowledgePointField = value;
                    this.RaisePropertyChanged("MainKnowledgePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionCategoryId {
            get {
                return this.QuestionCategoryIdField;
            }
            set {
                if ((this.QuestionCategoryIdField.Equals(value) != true)) {
                    this.QuestionCategoryIdField = value;
                    this.RaisePropertyChanged("QuestionCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionDisplayTypeId {
            get {
                return this.QuestionDisplayTypeIdField;
            }
            set {
                if ((this.QuestionDisplayTypeIdField.Equals(value) != true)) {
                    this.QuestionDisplayTypeIdField = value;
                    this.RaisePropertyChanged("QuestionDisplayTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionId {
            get {
                return this.QuestionIdField;
            }
            set {
                if ((this.QuestionIdField.Equals(value) != true)) {
                    this.QuestionIdField = value;
                    this.RaisePropertyChanged("QuestionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short QuestionLevel {
            get {
                return this.QuestionLevelField;
            }
            set {
                if ((this.QuestionLevelField.Equals(value) != true)) {
                    this.QuestionLevelField = value;
                    this.RaisePropertyChanged("QuestionLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuestionQuality {
            get {
                return this.QuestionQualityField;
            }
            set {
                if ((this.QuestionQualityField.Equals(value) != true)) {
                    this.QuestionQualityField = value;
                    this.RaisePropertyChanged("QuestionQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double QuestionSortingScore {
            get {
                return this.QuestionSortingScoreField;
            }
            set {
                if ((this.QuestionSortingScoreField.Equals(value) != true)) {
                    this.QuestionSortingScoreField = value;
                    this.RaisePropertyChanged("QuestionSortingScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId {
            get {
                return this.SectionIdField;
            }
            set {
                if ((this.SectionIdField.Equals(value) != true)) {
                    this.SectionIdField = value;
                    this.RaisePropertyChanged("SectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SupportOnline {
            get {
                return this.SupportOnlineField;
            }
            set {
                if ((this.SupportOnlineField.Equals(value) != true)) {
                    this.SupportOnlineField = value;
                    this.RaisePropertyChanged("SupportOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseRange {
            get {
                return this.UseRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.UseRangeField, value) != true)) {
                    this.UseRangeField = value;
                    this.RaisePropertyChanged("UseRange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] UseRangeIds {
            get {
                return this.UseRangeIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.UseRangeIdsField, value) != true)) {
                    this.UseRangeIdsField = value;
                    this.RaisePropertyChanged("UseRangeIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniversityStageEnum", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.Enum.TiMingCe")]
    public enum UniversityStageEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UndergraduateFirstBatch = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UndergraduateSecondBatch = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        College = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undergraduate_All = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecommendUniversityEntity", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.View")]
    [System.SerializableAttribute()]
    public partial class RecommendUniversityEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvinceIdOfSchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceNameOfSchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankingRangeBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RankingRangeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UniversityRankingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvinceIdOfSchool {
            get {
                return this.ProvinceIdOfSchoolField;
            }
            set {
                if ((this.ProvinceIdOfSchoolField.Equals(value) != true)) {
                    this.ProvinceIdOfSchoolField = value;
                    this.RaisePropertyChanged("ProvinceIdOfSchool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProvinceNameOfSchool {
            get {
                return this.ProvinceNameOfSchoolField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceNameOfSchoolField, value) != true)) {
                    this.ProvinceNameOfSchoolField = value;
                    this.RaisePropertyChanged("ProvinceNameOfSchool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RankingRangeBegin {
            get {
                return this.RankingRangeBeginField;
            }
            set {
                if ((this.RankingRangeBeginField.Equals(value) != true)) {
                    this.RankingRangeBeginField = value;
                    this.RaisePropertyChanged("RankingRangeBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RankingRangeEnd {
            get {
                return this.RankingRangeEndField;
            }
            set {
                if ((this.RankingRangeEndField.Equals(value) != true)) {
                    this.RankingRangeEndField = value;
                    this.RaisePropertyChanged("RankingRangeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolLogo {
            get {
                return this.SchoolLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolLogoField, value) != true)) {
                    this.SchoolLogoField = value;
                    this.RaisePropertyChanged("SchoolLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolName {
            get {
                return this.SchoolNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolNameField, value) != true)) {
                    this.SchoolNameField = value;
                    this.RaisePropertyChanged("SchoolName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScoreLine {
            get {
                return this.ScoreLineField;
            }
            set {
                if ((this.ScoreLineField.Equals(value) != true)) {
                    this.ScoreLineField = value;
                    this.RaisePropertyChanged("ScoreLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniversityRanking {
            get {
                return this.UniversityRankingField;
            }
            set {
                if ((this.UniversityRankingField.Equals(value) != true)) {
                    this.UniversityRankingField = value;
                    this.RaisePropertyChanged("UniversityRanking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCreateTiMingCeDocumentRequest", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.Request")]
    [System.SerializableAttribute()]
    public partial class GetCreateTiMingCeDocumentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.ArtsOrScienceEnum ArtsOrScienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.CourseJuanzi[] CourseJuanZiResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProvinceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Test.TiMingCe.TiMingCeTypeEnum TiMingCeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.ArtsOrScienceEnum ArtsOrScience {
            get {
                return this.ArtsOrScienceField;
            }
            set {
                if ((this.ArtsOrScienceField.Equals(value) != true)) {
                    this.ArtsOrScienceField = value;
                    this.RaisePropertyChanged("ArtsOrScience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.CourseJuanzi[] CourseJuanZiResult {
            get {
                return this.CourseJuanZiResultField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseJuanZiResultField, value) != true)) {
                    this.CourseJuanZiResultField = value;
                    this.RaisePropertyChanged("CourseJuanZiResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProvinceId {
            get {
                return this.ProvinceIdField;
            }
            set {
                if ((this.ProvinceIdField.Equals(value) != true)) {
                    this.ProvinceIdField = value;
                    this.RaisePropertyChanged("ProvinceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentNo {
            get {
                return this.StudentNoField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNoField, value) != true)) {
                    this.StudentNoField = value;
                    this.RaisePropertyChanged("StudentNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Test.TiMingCe.TiMingCeTypeEnum TiMingCeType {
            get {
                return this.TiMingCeTypeField;
            }
            set {
                if ((this.TiMingCeTypeField.Equals(value) != true)) {
                    this.TiMingCeTypeField = value;
                    this.RaisePropertyChanged("TiMingCeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseJuanzi", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.TiMingCe.Request")]
    [System.SerializableAttribute()]
    public partial class CourseJuanzi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JuanZiResultIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JuanZiResultId {
            get {
                return this.JuanZiResultIdField;
            }
            set {
                if ((this.JuanZiResultIdField.Equals(value) != true)) {
                    this.JuanZiResultIdField = value;
                    this.RaisePropertyChanged("JuanZiResultId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiMingCeTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/YunXuePing.Model.Enum.TiMingCe")]
    public enum TiMingCeTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoneSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HaveSet = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TiMingCe.ITiMingCe")]
    public interface ITiMingCe {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiMingCe/GetStudentTiMingCeData", ReplyAction="http://tempuri.org/ITiMingCe/GetStudentTiMingCeDataResponse")]
        Test.TiMingCe.ServiceResultOfTiMingCeEntityTca8ElYk GetStudentTiMingCeData(Test.TiMingCe.GetStudentTiMingCeDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiMingCe/GetStudentTiMingCeData", ReplyAction="http://tempuri.org/ITiMingCe/GetStudentTiMingCeDataResponse")]
        System.Threading.Tasks.Task<Test.TiMingCe.ServiceResultOfTiMingCeEntityTca8ElYk> GetStudentTiMingCeDataAsync(Test.TiMingCe.GetStudentTiMingCeDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiMingCe/CreateTiMingCeDocument", ReplyAction="http://tempuri.org/ITiMingCe/CreateTiMingCeDocumentResponse")]
        Test.TiMingCe.ServiceResultOfbase64Binary CreateTiMingCeDocument(Test.TiMingCe.GetCreateTiMingCeDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiMingCe/CreateTiMingCeDocument", ReplyAction="http://tempuri.org/ITiMingCe/CreateTiMingCeDocumentResponse")]
        System.Threading.Tasks.Task<Test.TiMingCe.ServiceResultOfbase64Binary> CreateTiMingCeDocumentAsync(Test.TiMingCe.GetCreateTiMingCeDocumentRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITiMingCeChannel : Test.TiMingCe.ITiMingCe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiMingCeClient : System.ServiceModel.ClientBase<Test.TiMingCe.ITiMingCe>, Test.TiMingCe.ITiMingCe {
        
        public TiMingCeClient() {
        }
        
        public TiMingCeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiMingCeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiMingCeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiMingCeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Test.TiMingCe.ServiceResultOfTiMingCeEntityTca8ElYk GetStudentTiMingCeData(Test.TiMingCe.GetStudentTiMingCeDataRequest request) {
            return base.Channel.GetStudentTiMingCeData(request);
        }
        
        public System.Threading.Tasks.Task<Test.TiMingCe.ServiceResultOfTiMingCeEntityTca8ElYk> GetStudentTiMingCeDataAsync(Test.TiMingCe.GetStudentTiMingCeDataRequest request) {
            return base.Channel.GetStudentTiMingCeDataAsync(request);
        }
        
        public Test.TiMingCe.ServiceResultOfbase64Binary CreateTiMingCeDocument(Test.TiMingCe.GetCreateTiMingCeDocumentRequest request) {
            return base.Channel.CreateTiMingCeDocument(request);
        }
        
        public System.Threading.Tasks.Task<Test.TiMingCe.ServiceResultOfbase64Binary> CreateTiMingCeDocumentAsync(Test.TiMingCe.GetCreateTiMingCeDocumentRequest request) {
            return base.Channel.CreateTiMingCeDocumentAsync(request);
        }
    }
}
